// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEjrRjYA-wC--yal5oo_tISoXwGqthZeI',
    appId: '1:636044962628:web:417140cb5085273cde8511',
    messagingSenderId: '636044962628',
    projectId: 'projeto-pet-d77dc',
    authDomain: 'projeto-pet-d77dc.firebaseapp.com',
    storageBucket: 'projeto-pet-d77dc.firebasestorage.app',
    measurementId: 'G-EWJQ97RDCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS9qi4fxPcBjJM5zCPfucZlHTq9SnbOYk',
    appId: '1:636044962628:android:184227079501a14cde8511',
    messagingSenderId: '636044962628',
    projectId: 'projeto-pet-d77dc',
    storageBucket: 'projeto-pet-d77dc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEjrRjYA-wC--yal5oo_tISoXwGqthZeI',
    appId: '1:636044962628:web:425652d9d706126fde8511',
    messagingSenderId: '636044962628',
    projectId: 'projeto-pet-d77dc',
    authDomain: 'projeto-pet-d77dc.firebaseapp.com',
    storageBucket: 'projeto-pet-d77dc.firebasestorage.app',
    measurementId: 'G-DJR11B2MQH',
  );
}
